package org.apache.geronimo.samples.daytrader;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * 2018-10-14T21:00:36.597+11:00
 * Generated source version: 3.1.12.redhat-1
 * 
 */
@WebServiceClient(name = "Trade", 
                  wsdlLocation = "classpath:TradeServices.wsdl",
                  targetNamespace = "http://daytrader.samples.geronimo.apache.org") 
public class Trade extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://daytrader.samples.geronimo.apache.org", "Trade");
    public final static QName TradeWSServices = new QName("http://daytrader.samples.geronimo.apache.org", "TradeWSServices");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/bfarr/projects/minimigration/daytrader-2.2.1-eap7/daytrader-2.2.1/modules/webservice/src/main/java/../resources/TradeServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Trade.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/bfarr/projects/minimigration/daytrader-2.2.1-eap7/daytrader-2.2.1/modules/webservice/src/main/java/../resources/TradeServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Trade(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Trade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Trade() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Trade(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Trade(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Trade(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TradeWSServices
     */
    @WebEndpoint(name = "TradeWSServices")
    public TradeWSServices getTradeWSServices() {
        return super.getPort(TradeWSServices, TradeWSServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TradeWSServices
     */
    @WebEndpoint(name = "TradeWSServices")
    public TradeWSServices getTradeWSServices(WebServiceFeature... features) {
        return super.getPort(TradeWSServices, TradeWSServices.class, features);
    }

}
